/**
 * Quiz-Daten für die Abschlussprüfung von Mission 1.
 */

export interface QuizQuestion {
  id: number;
  title: string;
  question: string;
  options: { id: string; text: string }[];
  correctId: string;
  explanation: string;
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    title: 'Wörterbuchattacke',
    question: 'Welches Passwort wird einer Wörterbuchattacke am wahrscheinlichsten am längsten standhalten?',
    options: [
      { id: 'A', text: 'Sommer2026!' },
      { id: 'B', text: 'HundMax2019' },
      { id: 'C', text: 'Kaffee-Wolke-Planet-Lampe' },
      { id: 'D', text: 'Qwertz123!' },
    ],
    correctId: 'C',
    explanation: 'Eine Wörterbuchattacke testet zuerst häufig verwendete Wörter, Namen und bekannte Passwortmuster. Eine lange Passphrase aus mehreren zufälligen Wörtern kommt in solchen Listen meist nicht vor und ist daher deutlich schwerer zu erraten.',
  },
  {
    id: 2,
    title: 'Passwort-Wiederverwendung',
    question: 'Du verwendest für dein Online-Banking und deinen Streaming-Dienst dasselbe starke Passwort. Der Streaming-Dienst wird gehackt und die Zugangsdaten gelangen ins Internet. Welches Risiko besteht?',
    options: [
      { id: 'A', text: 'Keines, da das Passwort stark ist.' },
      { id: 'B', text: 'Angreifer können versuchen, dieselben Zugangsdaten auch beim Online-Banking zu verwenden.' },
      { id: 'C', text: 'Das Passwort wird automatisch ungültig.' },
      { id: 'D', text: 'Nur der Streaming-Account ist betroffen.' },
    ],
    correctId: 'B',
    explanation: 'Viele Angreifer probieren gestohlene Zugangsdaten automatisch bei anderen Diensten aus. Deshalb sollte jedes Konto ein eigenes Passwort besitzen.',
  },
  {
    id: 3,
    title: 'Brute Force',
    question: 'Welches Passwort ist gegen eine reine Brute-Force-Attacke am besten geschützt?',
    options: [
      { id: 'A', text: 'Hallo123' },
      { id: 'B', text: 'Sommer2026!' },
      { id: 'C', text: 'T9$kL2@qWp7!Mz4#' },
      { id: 'D', text: 'Passwort123!' },
    ],
    correctId: 'C',
    explanation: 'Je länger und zufälliger ein Passwort ist, desto mehr Kombinationen muss ein Angreifer ausprobieren. Das macht Brute-Force-Angriffe deutlich aufwendiger.',
  },
  {
    id: 4,
    title: 'Persönliche Informationen',
    question: 'Ein Angreifer findet auf deinem öffentlichen Profil: Hund heißt Nami, Geburtsjahr 1998, Lieblingsverein Dortmund. Welches Passwort wird er vermutlich zuerst ausprobieren?',
    options: [
      { id: 'A', text: '#4FgP!zQwL8' },
      { id: 'B', text: 'Nami1998!' },
      { id: 'C', text: 'RegenstuhlZugKakao' },
      { id: 'D', text: '8xQ$4Lm!vP' },
    ],
    correctId: 'B',
    explanation: 'Angreifer kombinieren häufig öffentlich verfügbare persönliche Informationen. Haustiernamen und Geburtsdaten gehören zu den häufigsten Bestandteilen unsicherer Passwörter.',
  },
  {
    id: 5,
    title: 'Tastaturmuster',
    question: 'Warum gelten Passwörter wie „qwertz123" oder „asdf1234" als unsicher?',
    options: [
      { id: 'A', text: 'Sie enthalten keine Sonderzeichen.' },
      { id: 'B', text: 'Sie folgen bekannten Tastaturmustern und werden bei Angriffen früh ausprobiert.' },
      { id: 'C', text: 'Sie sind immer kürzer als 12 Zeichen.' },
      { id: 'D', text: 'Sie funktionieren nur auf deutschen Tastaturen.' },
    ],
    correctId: 'B',
    explanation: 'Tastaturmuster gehören zu den bekanntesten Passwortmustern und sind in vielen Passwortlisten bereits enthalten.',
  },
  {
    id: 6,
    title: 'Passwort-Manager',
    question: 'Ein Kollege benutzt für jedes Konto ein anderes Passwort und nutzt einen Passwort-Manager. Wie bewertest du dieses Verhalten?',
    options: [
      { id: 'A', text: 'Unsicher, weil alle Passwörter an einem Ort gespeichert sind.' },
      { id: 'B', text: 'Sicher, weil jedes Konto ein eigenes starkes Passwort besitzt.' },
      { id: 'C', text: 'Unsicher, weil Passwörter immer auswendig gelernt werden sollten.' },
      { id: 'D', text: 'Sicher nur, wenn alle Passwörter identisch sind.' },
    ],
    correctId: 'B',
    explanation: 'Ein Passwort-Manager ermöglicht lange, zufällige und einzigartige Passwörter für jedes Konto. Das gilt als empfohlene Vorgehensweise.',
  },
  {
    id: 7,
    title: 'Passphrase',
    question: 'Welche Aussage beschreibt eine sichere Passphrase am besten?',
    options: [
      { id: 'A', text: 'Sie sollte möglichst viele Zahlen enthalten.' },
      { id: 'B', text: 'Mehrere zufällige Wörter können sicherer sein als ein kurzes komplexes Passwort.' },
      { id: 'C', text: 'Sie darf keine Leerzeichen enthalten.' },
      { id: 'D', text: 'Sie sollte möglichst kurz sein.' },
    ],
    correctId: 'B',
    explanation: 'Eine lange Passphrase aus zufälligen Wörtern ist leicht zu merken und besitzt durch ihre Länge eine sehr hohe Sicherheit.',
  },
  {
    id: 8,
    title: 'Das Post-it',
    question: 'Ein Mitarbeiter verwendet ein komplexes Passwort (fK8!Lp#93Qx@Tn), klebt es jedoch auf einen Zettel neben seinen Monitor. Wie sollte dieses Passwort bewertet werden?',
    options: [
      { id: 'A', text: 'Sehr sicher, da es komplex ist.' },
      { id: 'B', text: 'Unsicher, weil jeder das Passwort leicht sehen oder fotografieren kann.' },
      { id: 'C', text: 'Sicher, solange niemand den Computer benutzt.' },
      { id: 'D', text: 'Sicher, weil Sonderzeichen enthalten sind.' },
    ],
    correctId: 'B',
    explanation: 'Ein starkes Passwort schützt nur, wenn es geheim bleibt. Ist es für andere sichtbar, verliert es seinen Sicherheitsvorteil.',
  },
  {
    id: 9,
    title: 'Passwortlänge',
    question: 'Ein Unternehmen erlaubt maximal acht Zeichen pro Passwort. Welcher Nachteil entsteht dadurch?',
    options: [
      { id: 'A', text: 'Wörterbuchattacken funktionieren nicht mehr.' },
      { id: 'B', text: 'Der mögliche Suchraum für Brute-Force-Angriffe wird deutlich kleiner.' },
      { id: 'C', text: 'Passwörter werden leichter merkbar.' },
      { id: 'D', text: 'Sonderzeichen können nicht verwendet werden.' },
    ],
    correctId: 'B',
    explanation: 'Kurze Passwörter besitzen deutlich weniger mögliche Kombinationen und können deshalb wesentlich schneller durch Brute Force ausprobiert werden.',
  },
  {
    id: 10,
    title: 'Gesamtabwägung',
    question: 'Welches dieser Passwörter würdest du insgesamt als am sichersten bewerten?',
    options: [
      { id: 'A', text: 'Sommer2026!' },
      { id: 'B', text: 'Nami01081998' },
      { id: 'C', text: 'Traktor1Wolke&Komet' },
      { id: 'D', text: 'Qwertz1407' },
    ],
    correctId: 'C',
    explanation: 'Die Passphrase ist lang, einzigartig und enthält keine persönlichen Informationen oder bekannte Muster. Dadurch ist sie sowohl gegen Wörterbuch- als auch gegen Brute-Force-Angriffe besonders widerstandsfähig.',
  },
  {
    id: 11,
    title: 'Zahlen am Ende',
    question: 'Welches Passwort gilt als am wenigsten sicher?',
    options: [
      { id: 'A', text: 'SonneRegenBergFluss' },
      { id: 'B', text: 'Passwort2026!' },
      { id: 'C', text: 'Mango-Kerze-Fenster-Stern' },
      { id: 'D', text: 'Vogel!Mond#Wiese7' },
    ],
    correctId: 'B',
    explanation: 'Viele Nutzer ergänzen lediglich eine Jahreszahl an ein bekanntes Wort. Solche Muster gehören zu den ersten Kombinationen, die Angreifer ausprobieren.',
  },
  {
    id: 12,
    title: 'Passwort ändern',
    question: 'Wann solltest du ein Passwort unbedingt ändern?',
    options: [
      { id: 'A', text: 'Alle sieben Tage.' },
      { id: 'B', text: 'Nur wenn es schwer zu merken ist.' },
      { id: 'C', text: 'Wenn du erfährst, dass der verwendete Dienst Opfer eines Datenlecks wurde.' },
      { id: 'D', text: 'Nur wenn dein Computer langsam wird.' },
    ],
    correctId: 'C',
    explanation: 'Wurde ein Dienst gehackt, könnten Zugangsdaten gestohlen worden sein. Das Passwort sollte dann sofort geändert werden – insbesondere, wenn es auch anderswo verwendet wurde.',
  },
  {
    id: 13,
    title: 'Das längste Passwort',
    question: 'Welche Aussage trifft am ehesten zu?',
    options: [
      { id: 'A', text: 'Sonderzeichen sind wichtiger als die Länge.' },
      { id: 'B', text: 'Die Länge eines Passworts trägt wesentlich zur Sicherheit bei.' },
      { id: 'C', text: 'Großbuchstaben reichen aus.' },
      { id: 'D', text: 'Zahlen machen ein Passwort automatisch sicher.' },
    ],
    correctId: 'B',
    explanation: 'Mit jedem zusätzlichen Zeichen wächst die Anzahl möglicher Kombinationen erheblich. Deshalb ist die Passwortlänge ein entscheidender Sicherheitsfaktor.',
  },
  {
    id: 14,
    title: 'Passwortgenerator',
    question: 'Warum gilt ein Passwortgenerator als sinnvoll?',
    options: [
      { id: 'A', text: 'Er erzeugt leicht zu erratende Passwörter.' },
      { id: 'B', text: 'Er erstellt lange und zufällige Passwörter, die schwer vorhersehbar sind.' },
      { id: 'C', text: 'Er verwendet immer denselben Aufbau.' },
      { id: 'D', text: 'Er speichert Passwörter automatisch öffentlich.' },
    ],
    correctId: 'B',
    explanation: 'Ein Passwortgenerator erstellt zufällige Passwörter mit hoher Entropie, die Menschen selbst meist nicht auswählen würden.',
  },
  {
    id: 15,
    title: 'Zwei Konten',
    question: 'Du hast für zwei verschiedene Webseiten unterschiedliche Passwörter gewählt. Warum ist das sinnvoll?',
    options: [
      { id: 'A', text: 'Dadurch laden Webseiten schneller.' },
      { id: 'B', text: 'Ein kompromittiertes Passwort gefährdet nicht automatisch das zweite Konto.' },
      { id: 'C', text: 'Dadurch werden Passwörter leichter merkbar.' },
      { id: 'D', text: 'Webseiten verlangen das grundsätzlich.' },
    ],
    correctId: 'B',
    explanation: 'Für jedes Konto sollte ein eigenes Passwort verwendet werden. So bleibt der Schaden auf einen einzelnen Dienst begrenzt.',
  },
  {
    id: 16,
    title: 'Das stärkste Muster',
    question: 'Welches Passwort weist die höchste Zufälligkeit auf?',
    options: [
      { id: 'A', text: 'AutoAutoAuto123' },
      { id: 'B', text: 'Sonne2026!' },
      { id: 'C', text: '4#xM8@LpQ!2vR7$k' },
      { id: 'D', text: 'Nami123456' },
    ],
    correctId: 'C',
    explanation: 'Zufällige Zeichenfolgen enthalten keine erkennbaren Muster oder persönlichen Informationen und sind dadurch besonders schwer vorherzusagen.',
  },
  {
    id: 17,
    title: 'Mehrere Geräte',
    question: 'Du meldest dich auf einem öffentlichen Computer an. Was solltest du anschließend tun?',
    options: [
      { id: 'A', text: 'Den Browser einfach schließen.' },
      { id: 'B', text: 'Das Passwort auf dem Desktop speichern.' },
      { id: 'C', text: 'Dich vollständig abmelden und keine Passwörter speichern lassen.' },
      { id: 'D', text: 'Den Bildschirm ausschalten.' },
    ],
    correctId: 'C',
    explanation: 'Auf gemeinsam genutzten Geräten sollten niemals Passwörter gespeichert werden. Eine vollständige Abmeldung verhindert unbefugten Zugriff.',
  },
  {
    id: 18,
    title: 'Das alte Passwort',
    question: 'Nach einer Passwortänderung lautet dein neues Passwort „Sommer2027!", vorher war es „Sommer2026!". Wie ist das zu bewerten?',
    options: [
      { id: 'A', text: 'Sehr sicher.' },
      { id: 'B', text: 'Unsicher, da lediglich eine kleine Änderung vorgenommen wurde.' },
      { id: 'C', text: 'Sicher, weil sich die Jahreszahl geändert hat.' },
      { id: 'D', text: 'Sicher, weil das Passwort länger geworden ist.' },
    ],
    correctId: 'B',
    explanation: 'Angreifer berücksichtigen häufig kleine Variationen bereits bekannter Passwörter. Eine vollständig neue Kombination ist deutlich sicherer.',
  },
  {
    id: 19,
    title: 'Passwort teilen',
    question: 'Ein Kollege bittet dich kurzfristig um dein Passwort, um eine Datei herunterzuladen. Wie solltest du reagieren?',
    options: [
      { id: 'A', text: 'Das Passwort kurz weitergeben und anschließend ändern.' },
      { id: 'B', text: 'Das Passwort auf einen Zettel schreiben.' },
      { id: 'C', text: 'Das Passwort nicht weitergeben und eine andere Lösung suchen.' },
      { id: 'D', text: 'Das Passwort per Chat senden.' },
    ],
    correctId: 'C',
    explanation: 'Passwörter sind persönlich und sollten niemals weitergegeben werden. Stattdessen sollten Freigaben oder gemeinsame Zugriffswege genutzt werden.',
  },
  {
    id: 20,
    title: 'Ähnliche Passwörter',
    question: 'Du verwendest folgende Passwörter: E-Mail: „Blume2026!", Online-Shop: „Blume2027!", Forum: „Blume2028!". Wie ist dieses Vorgehen zu bewerten?',
    options: [
      { id: 'A', text: 'Sicher, da alle Passwörter unterschiedlich sind.' },
      { id: 'B', text: 'Unsicher, da die Passwörter leicht voneinander abgeleitet werden können.' },
      { id: 'C', text: 'Sicher, weil unterschiedliche Jahreszahlen verwendet wurden.' },
      { id: 'D', text: 'Sicher, solange Sonderzeichen enthalten sind.' },
    ],
    correctId: 'B',
    explanation: 'Kleine Abwandlungen eines Passworts gelten nicht als unabhängige Passwörter. Wird eines bekannt, lassen sich die anderen häufig leicht erraten.',
  },
  {
    id: 21,
    title: 'Passwort merken',
    question: 'Welches Vorgehen ist am sinnvollsten, wenn du dir viele starke Passwörter merken musst?',
    options: [
      { id: 'A', text: 'Für alle Konten dasselbe Passwort verwenden.' },
      { id: 'B', text: 'Einen Passwort-Manager nutzen.' },
      { id: 'C', text: 'Alle Passwörter auf einen Zettel neben den Monitor kleben.' },
      { id: 'D', text: 'Die Passwörter möglichst kurz wählen.' },
    ],
    correctId: 'B',
    explanation: 'Ein Passwort-Manager hilft dabei, für jedes Konto ein eigenes starkes Passwort zu verwenden, ohne sie auswendig lernen zu müssen.',
  },
  {
    id: 22,
    title: 'Phishing',
    question: 'Du erhältst eine E-Mail deiner "Bank", in der du aufgefordert wirst, dein Passwort über einen Link zu bestätigen. Wie solltest du reagieren?',
    options: [
      { id: 'A', text: 'Sofort auf den Link klicken.' },
      { id: 'B', text: 'Das Passwort eingeben, wenn das Logo echt aussieht.' },
      { id: 'C', text: 'Den Link nicht verwenden und stattdessen die offizielle Webseite der Bank selbst aufrufen.' },
      { id: 'D', text: 'Die E-Mail an Freunde weiterleiten.' },
    ],
    correctId: 'C',
    explanation: 'Phishing-E-Mails versuchen, Passwörter zu stehlen. Melde dich deshalb immer direkt über die offizielle Webseite oder App an.',
  },
  {
    id: 23,
    title: 'Das beste Passwort',
    question: 'Welches Passwort würdest du wählen?',
    options: [
      { id: 'A', text: 'Max2001!' },
      { id: 'B', text: 'Qwertz987' },
      { id: 'C', text: 'Kakao-Zebra-Lampe-Regen' },
      { id: 'D', text: 'Deutschland2026' },
    ],
    correctId: 'C',
    explanation: 'Die Passphrase ist lang, enthält keine bekannten Muster und keine persönlichen Informationen. Dadurch ist sie deutlich widerstandsfähiger gegen Angriffe.',
  },
  {
    id: 24,
    title: 'Passwort zurücksetzen',
    question: 'Ein Dienst informiert dich darüber, dass dein Passwort möglicherweise gestohlen wurde. Was solltest du zuerst tun?',
    options: [
      { id: 'A', text: 'Abwarten, ob etwas passiert.' },
      { id: 'B', text: 'Das Passwort sofort ändern und – falls wiederverwendet – auch bei anderen Diensten ersetzen.' },
      { id: 'C', text: 'Nur den Benutzernamen ändern.' },
      { id: 'D', text: 'Den Computer neu starten.' },
    ],
    correctId: 'B',
    explanation: 'Nach einem vermuteten Datenleck sollte das betroffene Passwort sofort ersetzt werden. Wurde es mehrfach verwendet, müssen auch diese Konten abgesichert werden.',
  },
  {
    id: 25,
    title: 'Das sicherste Verhalten',
    question: 'Welche Kombination von Maßnahmen sorgt insgesamt für die höchste Passwortsicherheit?',
    options: [
      { id: 'A', text: 'Ein langes Passwort für alle Konten.' },
      { id: 'B', text: 'Kurze Passwörter mit vielen Sonderzeichen.' },
      { id: 'C', text: 'Für jedes Konto ein einzigartiges langes Passwort und ein Passwort-Manager.' },
      { id: 'D', text: 'Das Passwort regelmäßig auf einem Zettel notieren.' },
    ],
    correctId: 'C',
    explanation: 'Die Kombination aus einzigartigen, langen Passwörtern und einem Passwort-Manager entspricht den heutigen Empfehlungen für einen sicheren Umgang mit Zugangsdaten.',
  },
];
